# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uZpg1KSt5By4jFBqHg7YpZoPFBnmdPOT
"""

!apt install g++-10 liblz4-dev && export CXX=g++-10

!pip install aestream

import aestream
import matplotlib.pyplot as plt
import time

# f = aestream.FileInput("g-007.aedat4", (346, 280))
# f = aestream.FileInput("l.aedat4", (250, 175))
f = aestream.FileInput("k.aedat4", (250, 175))

s = 0
st = time.time()
with f as stream:
    # In this case, we read() every 1ms
    interval = 0.001
    c = 0
    t_0 = time.time()

    # Loop forever
    while stream.is_streaming():
        # When 1 ms passed...
        if t_0 + interval <= time.time():
            # Grab a tensor of the events arriving during the past 1ms
            frame = stream.read(backend="torch")

            plt.imshow(frame.clip(0, 1).T)

            # Sum up the events and increment frame counter
            s += frame.sum()
            c += 1

            # Reset the time so we're again counting to 1ms
            t_0 = time.time()

print(
    f"{c} frames of 1ms each read in {time.time() - st:.3}s containing a total of {s} events"
)